# Tablas Fuertes
-- CLIENTES
-- EMPLEADOS
-- TIPO_TRANSPORTE
-- CONDUCTOR
-- TIPO VIAJE

# Tablas debiles
-- LICENCIA
-- TRANSPORTE
-- DESTINO
-- COMPRA
-- CANCELACION COMPRA
-- FACTURA

# ----------------------------------------------------------------
DROP DATABASE IF EXISTS AGENCIA_VIAJES;
CREATE DATABASE AGENCIA_VIAJES;
USE  AGENCIA_VIAJES;
DROP TABLE IF EXISTS CLIENTES;
CREATE TABLE CLIENTES(

	CLIENTES_CED 	VARCHAR(10) NOT NULL PRIMARY KEY,
        CLIENTES_NOM 	VARCHAR(40) NOT NULL,
        CLIENTES_APE 	VARCHAR(40) NOT NULL,
        CLIENTES_DIR 	VARCHAR(50),
	CLIENTES_EDA 	INT,
        CLIENTES_NAC 	VARCHAR(15),
        CLIENTES_ES_C	ENUM('CASADO', 'SOLTERO', 'VIUDO') NOT NULL,
	CLIENTES_TEL	VARCHAR(10),
	CLIENTES_ES_R	VARCHAR(25)
); 


DROP TABLE IF EXISTS EMPLEADOS;
CREATE TABLE EMPLEADOS(

	EMPLEADOS_CED 	VARCHAR(10) NOT NULL PRIMARY KEY,
        EMPLEADOS_NOM 	VARCHAR(40) NOT NULL,
        EMPLEADOS_APE 	VARCHAR(40) NOT NULL,
        EMPLEADOS_DIR 	VARCHAR(50) NOT NULL,
	EMPLEADOS_EDA 	INT	    NOT NULL,
        EMPLEADOS_ES_C	ENUM('CASADO', 'SOLTERO', 'VIUDO'),
	EMPLEADOS_TEL	VARCHAR(10),
	EMPLEADOS_SAL	DOUBLE
);


DROP TABLE IF EXISTS TIPO_VIAJE;
CREATE TABLE  TIPO_VIAJE(
	TIPO_VIAJE_COD	INT AUTO_INCREMENT PRIMARY KEY,
        TIPO_VIAJE_TIP 	VARCHAR(25) NOT NULL,
        TIPO_VIAJE_DES	VARCHAR(40),
	TIPO_VIAJE_PRE	DOUBLE NOT NULL
);

DROP TABLE IF EXISTS TIPO_TRANSPORTE;
CREATE TABLE TIPO_TRANSPORTE(

	TIPO_TRANSPORTE_COD INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TIPO_TRANSPORTE_NOM VARCHAR(15),
	TIPO_TRANSPORTE_ASI INT DEFAULT 1		
); 

DROP TABLE IF EXISTS CONDUCTOR;
CREATE TABLE CONDUCTOR(

	CONDUCTOR_CED	VARCHAR(10) NOT NULL PRIMARY KEY,
	CONDUCTOR_NOM	VARCHAR(40) NOT NULL,
	CONDUCTOR_APE	VARCHAR(40),
	CONDUCTOR_TEL	VARCHAR(10)
);

DROP TABLE IF EXISTS LICENCIA;
CREATE TABLE LICENCIA(
	LICENCIA_COD INT AUTO_INCREMENT PRIMARY KEY,
	LICENCIA_TIP VARCHAR(2) NOT NULL,
	LICENCIA_FE_I DATE NOT NULL,
	LICENCIA_FE_F DATE NOT NULL,
	LICENCIA_FK_CON VARCHAR(10) NOT NULL,
	CONSTRAINT REL_LIC_CON FOREIGN KEY(LICENCIA_FK_CON) REFERENCES CONDUCTOR(CONDUCTOR_CED) ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS TRANSPORTE;
CREATE TABLE TRANSPORTE(

	TRANSPORTE_COD	   INT AUTO_INCREMENT PRIMARY KEY,
        TRANSPORTE_MAT	   VARCHAR(20) NOT NULL,
	TRANSPORTE_COL 	   VARCHAR(20),
	TRANSPORTE_AG_F    VARCHAR(4),   
	TRANSPORTE_FK_TI_T INT NOT NULL,
	TRANSPORTE_FK_CON  VARCHAR(10) NOT NULL,
	CONSTRAINT REL_TRA_TIP_TR FOREIGN KEY(TRANSPORTE_FK_TI_T) REFERENCES TIPO_TRANSPORTE(TIPO_TRANSPORTE_COD) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REL_TRA_CON FOREIGN KEY(TRANSPORTE_FK_CON) REFERENCES CONDUCTOR(CONDUCTOR_CED) ON DELETE RESTRICT ON UPDATE RESTRICT
); 


DROP TABLE IF EXISTS DESTINO;
CREATE TABLE DESTINO(

	DESTINO_COD 	INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
        DESTINO_LUG 	VARCHAR(40) NOT NULL,
        DESTINO_DIR	VARCHAR(40) NOT NULL,
        DESTINO_CIU	VARCHAR(50) NOT NULL,
	DESTINO_PAI 	VARCHAR(50) NOT NULL,
	DESTINO_FK_TI_V INT NOT NULL,
	CONSTRAINT REL_DES_TIP_V  FOREIGN   KEY(DESTINO_FK_TI_V)  REFERENCES TIPO_VIAJE (TIPO_VIAJE_COD) ON DELETE RESTRICT ON UPDATE RESTRICT
	   
); 

DROP TABLE IF EXISTS COMPRA;
CREATE TABLE COMPRA(
	COMPRA_COD		INT AUTO_INCREMENT PRIMARY KEY,
	COMPRA_FEC		DATE NOT NULL,
	COMPRA_NU_B		INT DEFAULT 1,
	COMPRA_FK_CLI 		VARCHAR(10) NOT NULL,
        COMPRA_FK_DES 		INT  NOT NULL,
	COMPRA_FK_TRA		INT  NOT NULL,
	COMPRA_FK_EMP		VARCHAR(10) NOT NULL,
	CONSTRAINT REL_COM_CLI  FOREIGN     KEY(COMPRA_FK_CLI)  REFERENCES CLIENTES     (CLIENTES_CED)      ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REL_COM_DES  FOREIGN     KEY(COMPRA_FK_DES)  REFERENCES DESTINO      (DESTINO_COD)       ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REL_COM_TRA  FOREIGN     KEY(COMPRA_FK_TRA)  REFERENCES TRANSPORTE   (TRANSPORTE_COD)    ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REL_COM_EMP  FOREIGN     KEY(COMPRA_FK_EMP)  REFERENCES EMPLEADOS    (EMPLEADOS_CED)     ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS CANCELAR_COMPRA;
CREATE TABLE CANCELAR_COMPRA(
	CANCELAR_COMPRA_COD  	      INT AUTO_INCREMENT PRIMARY KEY,
	CANCELAR_COMPRA_FK_COM        INT  NOT NULL,
	CANCELAR_COMPRA_FK_EMP        VARCHAR(10)  NOT NULL,
	CANCELAR_COMPRA_FEC	      DATE	   NOT NULL,
	CONSTRAINT REL_CAN_COM_COM  FOREIGN     KEY(CANCELAR_COMPRA_FK_COM)  REFERENCES COMPRA(COMPRA_COD)    ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT REL_CAN_COM_EMP  FOREIGN     KEY(CANCELAR_COMPRA_FK_EMP)  REFERENCES EMPLEADOS    (EMPLEADOS_CED)  ON DELETE RESTRICT ON UPDATE RESTRICT
);


DROP TABLE IF EXISTS FACTURA;
CREATE TABLE FACTURA(
	FACTURA_COD 	   INT AUTO_INCREMENT PRIMARY KEY,
	FACTURA_OBS	   VARCHAR(25),
	FACTURA_FEC	   DATE	        NOT NULL,
	FACTURA_FK_COM     INT  NOT NULL,
	FACTURA_SUB	   DOUBLE NOT NULL,
	FACTURA_TOT	   DOUBLE NOT NULL,
	CONSTRAINT         REL_FAC_COM  FOREIGN KEY(FACTURA_FK_COM)  REFERENCES COMPRA  (COMPRA_COD)  ON DELETE RESTRICT ON UPDATE RESTRICT
);